### ISSUE TITLE
Doesn't work with Kotlin 1.9.20

### ISSUE THREAD

**Issue by avwie** [dead8309/tailwind-kt#3]
## 🐛 Describe the bug
When upgrading to 1.9.20 the `setupTailwindProject` doesn't work anymore.

## ⚠️ Current behavior
Gradle crashes with:
```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.gradle.targets.js.dsl.KotlinJsBrowserDsl.commonWebpackConfig(kotlin.jvm.functions.Function1)'
	at kizzy.tailwind.utils.SetupTailwindProjectKt$setupTailwindProject$1$1.invoke(SetupTailwindProject.kt:10)
	at kizzy.tailwind.utils.SetupTailwindProjectKt$setupTailwindProject$1$1.invoke(SetupTailwindProject.kt:9)
```
